fix(yt): remove unnecessary match

diff --git a/.local/bin/yt b/.local/bin/yt
--- a/.local/bin/yt
+++ b/.local/bin/yt
@@ -104,7 +104,7 @@ while true; do
     -m|--download-music) shift; download_music "$1"; exit 0 ;;
     -n|--number) shift; NUMBER_OF_RESULTS="$1"; shift ;;
     -p|--play) shift; play "$1"; exit 0 ;;
-    -*|--*) echo "yt: error: unknown option: $1" >&2; exit 1 ;;
+    -*) echo "yt: error: unknown option: $1" >&2; exit 1 ;;
     *) QUERY=$(sed 's/ /+/g' <<< "$@"); break ;;
   esac
 done
